# Generated by Django 4.2.13 on 2024-06-26 16:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EventModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "base_event_id",
                    models.CharField(max_length=10, verbose_name="base event id"),
                ),
                ("event_id", models.CharField(max_length=10, verbose_name="event id")),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                ("start_date_time", models.DateTimeField()),
                ("end_date_time", models.DateTimeField()),
                (
                    "start_date",
                    models.DateField(blank=True, null=True, verbose_name="start date"),
                ),
                (
                    "start_time",
                    models.TimeField(blank=True, null=True, verbose_name="start time"),
                ),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="end date"),
                ),
                (
                    "end_time",
                    models.TimeField(blank=True, null=True, verbose_name="end time"),
                ),
                ("min_price", models.FloatField(default=0, verbose_name="min price")),
                ("max_price", models.FloatField(default=0, verbose_name="max price")),
                ("created_at", models.DateField(auto_now_add=True)),
                ("updated_at", models.DateField(auto_now=True)),
            ],
            options={"ordering": ["created_at"]},
        )
    ]
